name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup variables
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential gnu-efi nasm

      - name: Build
        run: make

      - name: Compress
        run: |
          mkdir -p abootsap-${VERSION}
          cp {build/asbootsap.efi,src/asbootsap.cfg.sample} abootsap-${VERSION}
          7z a asbootsap-${VERSION}.7z abootsap-${VERSION}

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            asbootsap-${{ env.VERSION }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
